# Generated by Django 5.2.7 on 2025-11-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sale_created_by_alter_product_sku_userprofile_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE api_product RENAME COLUMN update_at TO updated_at;",
            reverse_sql="ALTER TABLE api_product RENAME COLUMN updated_at TO update_at;"
        ),
    ]
