# Generated by Django 5.2.7 on 2025-11-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20251104_1126'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE api_product ALTER COLUMN sku DROP NOT NULL;",
            reverse_sql="ALTER TABLE api_product ALTER COLUMN sku SET NOT NULL;"
        ),
    ]
