# Generated by Django 5.2.7 on 2025-11-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20251104_1156'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE api_product SET reorder_level = 3 WHERE reorder_level = 10;",
            reverse_sql="UPDATE api_product SET reorder_level = 10 WHERE reorder_level = 3;"
        ),
    ]
