# Generated by Django 5.2.7 on 2025-11-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20251104_1222'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE api_userprofile 
            SET role = CASE 
                WHEN role IN ('admin', 'manager', 'staff', 'viewer') THEN 'cashier'
                WHEN role = 'super_admin' THEN 'super_admin'
                ELSE 'cashier'
            END;
            """,
            reverse_sql="""
            -- No reverse operation needed as we're simplifying roles
            """
        ),
    ]
