# Generated by Django 5.2.7 on 2025-11-11 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20251105_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Hafshat Kidz', max_length=255)),
                ('store_address', models.TextField(default='123 Liberation Road, Accra, Ghana')),
                ('store_phone', models.CharField(default='+233 24 123 4567', max_length=50)),
                ('store_email', models.EmailField(default='info@hafshatkidz.com', max_length=254)),
                ('currency', models.CharField(default='GHS', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=12.5, max_digits=5)),
                ('receipt_footer', models.TextField(default='Thank you for shopping with us!')),
                ('auto_open_cash_drawer', models.BooleanField(default=True)),
                ('print_receipts', models.BooleanField(default=True)),
                ('ask_for_customer_info', models.BooleanField(default=False)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('daily_sales_report', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, related_name='settings_updates', to='auth.user')),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('sale', 'Sale Notification'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to='api.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='notifications', to='auth.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
